CREATE TABLE IF NOT EXISTS _user (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID NOT NULL, 
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
